# Use this config for easy local debugging: only generate witness on CPU, no proofs

eth_prover:
  app_bin_path: "../artifacts/app.bin"
  mode: "cpu_witness"
  cache_policy: "on_failure"
  ethproofs_submission: "off"
  block_mod: 1
  prover_id: 0
  on_failure: "continue"
  prometheus_port: 9898

